services:
  backend:
    build: ./mern/backend
    ports:
      - "5050:5050" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb
    healthcheck:
      test: |
        curl -f http://localhost:5050/startup &&
        curl -f http://localhost:5050/ready &&
        curl -f http://localhost:5050/health
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s


  frontend:
    build: ./mern/frontend
    ports:
      - "5173:5173"  
    networks:
      - mern_network
    environment:
      VITE_API_URL: http://3.91.218.109:5050
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    
    


  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally

