---
- name: Deploy MERN Stack using Docker
  hosts: localhost
  become: true
  connection: local
  vars:
    vars_files:
      - group_vars/docker.yml
      
  tasks:
    - name: Login to DockerHub
      ansible.builtin.shell: |
        echo "{{ docker_password }}" | docker login -u "{{ docker_username }}" --password-stdin
      no_log: true
